
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:serviceaccount:kube-system:clerk-controller
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:serviceaccount:kube-system:clerk-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:serviceaccount:kube-system:clerk-controller
subjects:
- kind: ServiceAccount
  name: clerk-controller
  namespace: kube-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clerk-controller

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: clerk
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: clerk
    spec:
      serviceAccountName: clerk-controller
      containers:
      - name: clerk
        image: jpweber/clerk:latest
        resources:
            requests:
                memory: "128Mi"
                cpu: "100m"
            limits:
                memory: "512Mi"
                cpu: "150m"