[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.2"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.31"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.3.1"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "v1.3.1"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.8"

