[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.8.10"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.31"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.3.0"

