kind: ConfigMap
apiVersion: v1
metadata:
  name: quartermaster
data:
  config.yaml: |-
    remoteEndpoint: "http://http-service-test.default.svc.cluster.local:8080/updates"
    resources:
      # - namespaces
      - pods
      - deployments
