kind: ConfigMap
apiVersion: v1
metadata:
  name: quartermaster
data:
  config.yaml: |-
    clusterName: "ClusterNAME"
    remoteEndpoint: "http://somehttpservice.default.svc.cluster.local:8080/updates"
    resources:
      - namespaces
      - pods
    deltaUpdates: false # false here will provide a full cluster object mapping for every change 
