
apiVersion: v1
kind: Namespace
metadata:
  name: heptio-qm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quartermaster-controller
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quartermaster-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quartermaster-controller
subjects:
- kind: ServiceAccount
  name: quartermaster-controller
  namespace: heptio-qm

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quartermaster-controller

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quartermaster
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: quartermaster
    spec:
      serviceAccountName: quartermaster-controller
      containers:
      - name: quartermaster
        image: <your image name> # provide your own image
        imagePullPolicy: Always
        resources:
            requests:
                memory: "128Mi"
                cpu: "100m"
            limits:
                memory: "512Mi"
                cpu: "150m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/quartermaster
      volumes:
      - name: config-volume
        configMap:
          name: quartermaster
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: quartermaster
data:
  config.yaml: |-
    clusterName: "ClusterNAME" # unique name for cluster quartermast is running in
    remoteEndpoint: "<remote endpoint to receive updates>" # receiver of the quatermaster payloads
    resources:
      - namespaces
      - pods
      - deployments
    deltaUpdates: true # true or false. False will send full cluster object. True sends just changes    
