apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: heptio-qm
spec:
  selector:
    app: echo
  ports:
  - name: http
    port: 80
    protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: echo
  namespace: heptio-qm
  labels:
    app: echo
spec:
  containers:
  - image: mendhak/http-https-echo
    name: echo
    imagePullPolicy: IfNotPresent

