apiVersion: v1
kind: Service
metadata:
  name: echo1
  namespace: tanzu-watch-proxy
spec:
  selector:
    app: echo1
  ports:
  - name: http
    port: 80
    protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: echo1
  namespace: tanzu-watch-proxy
  labels:
    app: echo1
spec:
  containers:
  - image: mendhak/http-https-echo
    name: echo
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: echo2
  namespace: tanzu-watch-proxy
spec:
  selector:
    app: echo2
  ports:
  - name: http
    port: 80
    protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: echo2
  namespace: tanzu-watch-proxy
  labels:
    app: echo2
spec:
  containers:
  - image: mendhak/http-https-echo
    name: echo
    imagePullPolicy: IfNotPresent

