apiVersion: v1
kind: Service
metadata:
  name: quartermeaster 
  namespace: heptio-qm
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  selector:
    app: quartermaster
  type: ClusterIP
