kind: ConfigMap
apiVersion: v1
metadata:
  name: quartermaster
  namespace: heptio-qm
data:
  config.yaml: |-
    clusterName: "dev-cluster"
    emitCacheDuration: 14400m
    # Minutes quartermaster should wait before attempting to re-process all objects inside of kubernetes.
    # If state of object during re-upload hasn't changed since last emit (meaning quartermaster still has
    # a cached record, the object will be dropped). This setting relates to client-go's resyncPeriod Setting this value
    # to 0 ensures no forced re-upload occurs. Specified with seconds (s), minutes (m), or hours (h).
    forceReuploadDuration: 500h
    remoteEndpoints:
    - type: http
      url: http://echo1/quartermaster
      usernameVar: USERNAME1
      passwordVar: PASSWORD1
      namespaces:
      - heptio-qm
    - type: http
      url: http://echo2/quartermaster
      usernameVar: USERNAME2
      passwordVar: PASSWORD2
    metadata:
      platform: baremetal
      region: east
    resources:
    - name: services
      assetId: svc
      pruneFields:
      - metadata.resourceVersion
      - metadata.generation
      - metadata.annotations
      - status.observedGeneration
    - name: namespaces
      assetId: ns
      pruneFields:
      - metadata.resourceVersion
      - metadata.generation
      - metadata.annotations
      - status.observedGeneration

