apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quartermaster
  namespace: heptio-qm
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: quartermaster
    spec:
      serviceAccountName: quartermaster-controller
      containers:
      - name: quartermaster
        image: your/image/name  # put your image name here
        imagePullPolicy: IfNotPresent
        resources:
            requests:
                memory: "128Mi"
                cpu: "100m"
            limits:
                memory: "512Mi"
                cpu: "150m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/quartermaster
        env:
        - name: USERNAME1
          valueFrom:
            secretKeyRef:
              name: quartermaster-creds-1
              key: username
        - name: PASSWORD1
          valueFrom:
            secretKeyRef:
              name: quartermaster-creds-1
              key: password
        - name: USERNAME2
          valueFrom:
            secretKeyRef:
              name: quartermaster-creds-2
              key: username
        - name: PASSWORD2
          valueFrom:
            secretKeyRef:
              name: quartermaster-creds-2
              key: password
      volumes:
      - name: config-volume
        configMap:
          name: quartermaster

