apiVersion: v1
kind: Secret
metadata:
  name: watch-proxy-creds-1
  namespace: tanzu-watch-proxy
type: Opaque
data:
  username: dXNlcjEK
  password: cGFzczEK
---
apiVersion: v1
kind: Secret
metadata:
  name: watch-proxy-creds-2
  namespace: tanzu-watch-proxy
type: Opaque
data:
  username: dXNlcjIK
  password: cGFzczIK

